# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a466959f5d53a7c60ec38b8a37f9a85545767a62116b135b4f88c85f51b465f83e64ff8c15c84823d8c00f4b5d2067048afef5c828d7d81d6e7280e0687ac30a

test:
  secret_key_base: 5f8705a130a68dd4deb495daab7a227ef3084adeb36f4b57c9a53a98736a9eedd0261fb7ffbca50d89dff15e48e58f216b9fe78518396a6c9e8b257269bce2bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
